name: Manual Rollback

on:
  workflow_dispatch:
    inputs:
      rollback_tag:
        description: "Enter the version tag to roll back to (e.g., v1.0.0)"
        required: true
        type: string

permissions:
  contents: read

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: spiritacr.azurecr.io
          username: spiritacr
          password: lSdbeMIO9eEmCLGyn/qFW3ti7ecDEorsTT81T5q8Q1+ACRCp2bHb

      - name: Pull and Re-tag Image
        run: |
          docker pull spiritacr.azurecr.io/sds-reports-api:${{ github.event.inputs.rollback_tag }}
          docker tag spiritacr.azurecr.io/sds-reports-api:${{ github.event.inputs.rollback_tag }} spiritacr.azurecr.io/sds-reports-api:latest
          docker push spiritacr.azurecr.io/sds-reports-api:latest
