name: polaris-reports-deployment

on:
  push:
    branches:
      - main
      
jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: feature/workflow_changes
      - name: Docker Login to Dev ACR
        uses: azure/docker-login@v1
        with:
          login-server: spiritacr.azurecr.io
          username: spiritacr
          password: lSdbeMIO9eEmCLGyn/qFW3ti7ecDEorsTT81T5q8Q1+ACRCp2bHb

      - name: Build and Push Dev Docker Image
        run: |
          docker build -t spiritacr.azurecr.io/sds-reports-api:${{ github.sha }} .
          docker tag spiritacr.azurecr.io/sds-reports-api:${{ github.sha }} spiritacr.azurecr.io/sds-reports-api:latest
          echo "Pushing Dev Docker image to ACR..."
          docker push spiritacr.azurecr.io/sds-reports-api:latest
